// @ts-nocheck
import { MAIN_STATS, SECONDARY_STAT_PRIORITY, BAPHOMET_SET_BONUSES, IFRIT_SET_BONUSES, CLASS_CONFIGS } from "./stats";

export function createSharedRuntimeApi({
  stateModule,
  catalogModule,
  profilesModule,
  statsModule,
  normalizeText,
  sanitizeClassLevel,
  escapeHtml,
  localizeText,
  getLocalizedCatalogField,
  getLocalizedCatalogLines,
  getLocalizedCatalogUpgradeLines,
  t,
  setLanguage,
  getCurrentLanguage,
}) {
  return {
    SLOT_CONFIG: catalogModule.SLOT_CONFIG,
    SPHERE_SLOT_CONFIG: catalogModule.SPHERE_SLOT_CONFIG,
    TROPHY_SLOT_CONFIG: catalogModule.TROPHY_SLOT_CONFIG,
    PET_CATEGORY_CONFIG: catalogModule.PET_CATEGORY_CONFIG,
    PET_MERGE_CONFIG: catalogModule.PET_MERGE_CONFIG,
    PET_MERGE_TOTAL_LIMIT: catalogModule.PET_MERGE_TOTAL_LIMIT,
    SPHERE_TYPE_ONE_TABS: catalogModule.SPHERE_TYPE_ONE_TABS,
    CLASS_CONFIGS,
    MAIN_STATS,
    SECONDARY_STAT_PRIORITY,
    BAPHOMET_SET_BONUSES,
    IFRIT_SET_BONUSES,
    PASSIVE_MORPH_RING_SLOT_KEY: catalogModule.PASSIVE_MORPH_RING_SLOT_KEY,
    state: stateModule.state,
    getActiveProfile: profilesModule.getActiveProfile,
    getSlotConfig: catalogModule.getSlotConfig,
    getSphereSlotConfig: catalogModule.getSphereSlotConfig,
    getTrophySlotConfig: catalogModule.getTrophySlotConfig,
    getItemsForEquipmentSlot: catalogModule.getItemsForEquipmentSlot,
    getSphereItemsForSlot: catalogModule.getSphereItemsForSlot,
    getTrophyItemsForSlot: catalogModule.getTrophyItemsForSlot,
    getPetItemsForCategory: catalogModule.getPetItemsForCategory,
    getPetMergeCounts: catalogModule.getPetMergeCounts,
    getPetMergeTotal: catalogModule.getPetMergeTotal,
    getPetMergeStats: catalogModule.getPetMergeStats,
    getLevelKeys: catalogModule.getLevelKeys,
    getDefaultUpgradeLevel: catalogModule.getDefaultUpgradeLevel,
    getValidUpgradeLevel: catalogModule.getValidUpgradeLevel,
    getAdjacentUpgradeLevel: catalogModule.getAdjacentUpgradeLevel,
    renderUpgradeStepperControl: catalogModule.renderUpgradeStepperControl,
    shouldDisplayUpgradeLevel: catalogModule.shouldDisplayUpgradeLevel,
    formatUpgradeSuffix: catalogModule.formatUpgradeSuffix,
    formatUpgradeTitleSuffix: catalogModule.formatUpgradeTitleSuffix,
    getParamsForLevel: catalogModule.getParamsForLevel,
    getLocalizedParamsForLevel: catalogModule.getLocalizedParamsForLevel,
    getMorphSphereRequiredLevel: catalogModule.getMorphSphereRequiredLevel,
    shouldShowSphereUpgrade: catalogModule.shouldShowSphereUpgrade,
    getSphereTypeOneTabForSlot: catalogModule.getSphereTypeOneTabForSlot,
    matchesEquipmentSlot: catalogModule.matchesEquipmentSlot,
    normalizeText,
    localizeText,
    getLocalizedCatalogField,
    getLocalizedCatalogLines,
    getLocalizedCatalogUpgradeLines,
    t,
    setLanguage,
    getCurrentLanguage,
    sanitizeClassLevel,
    normalizeProfileRecord: profilesModule.normalizeProfileRecord,
    renderItemIcon: statsModule.renderItemIcon,
    escapeHtml,
    parseNumericStat: statsModule.parseNumericStat,
    addNumericStat: statsModule.addNumericStat,
    addStatCollection: statsModule.addStatCollection,
    addStatWithRules: statsModule.addStatWithRules,
    createCollectedStatsBucket: statsModule.createCollectedStatsBucket,
    collectPetSelectionIntoBucket: statsModule.collectPetSelectionIntoBucket,
    collectItemParamsIntoBucket: statsModule.collectItemParamsIntoBucket,
    getDisplayStatsFromMap: statsModule.getDisplayStatsFromMap,
    computeBaseClassStat: statsModule.computeBaseClassStat,
    formatStatNumber: statsModule.formatStatNumber,
    formatStatValue: statsModule.formatStatValue,
    formatBoardPrimaryValue: statsModule.formatBoardPrimaryValue,
    saveProfilesState: stateModule.saveProfilesState,
    saveActiveProfileIdState: stateModule.saveActiveProfileIdState,
    saveClassState: stateModule.saveClassState,
    saveEquippedState: stateModule.saveEquippedState,
    saveSphereEquippedState: stateModule.saveSphereEquippedState,
    saveTrophyEquippedState: stateModule.saveTrophyEquippedState,
    savePetEquippedState: stateModule.savePetEquippedState,
    saveWorkspaceTabState: stateModule.saveWorkspaceTabState,
    applyProfileToState: profilesModule.applyProfileToState,
    setActiveProfile: profilesModule.setActiveProfile,
    createNewProfile: profilesModule.createNewProfile,
    saveActiveProfileExplicitly: profilesModule.saveActiveProfileExplicitly,
    copyActiveProfile: profilesModule.copyActiveProfile,
    deleteActiveProfile: profilesModule.deleteActiveProfile,
  };
}
